//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY.DataLayer.Modles
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTB()
        {
            this.FromTb = new HashSet<FromTb>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string Writer { get; set; }
        public string Publishare { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FromTb> FromTb { get; set; }
    }
}
