//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY.DataLayer.Modles
{
    using System;
    using System.Collections.Generic;
    
    public partial class FromTb
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Type { get; set; }
    
        public virtual BookTB BookTB { get; set; }
        public virtual CustomerTB CustomerTB { get; set; }
    }
}
