//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY.DataLayer.Modles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library_DBEntities : DbContext
    {
        public Library_DBEntities()
            : base("name=Library_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookTB> BookTB { get; set; }
        public virtual DbSet<CustomerTB> CustomerTB { get; set; }
        public virtual DbSet<FromTb> FromTb { get; set; }
    }
}
